---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
  - name: Install the required packages
    yum:
      name:
        - curl
        - wget
        - bind-utils
        - telnet
      state: installed
