---
- hosts: localhost
  gather_facts: false
  become: yes
  tasks:

  - name: Update the Operating System with latest updates
    yum:
      name: "*"
      state: latest
      update_cache: yes

  - name: Install the required packages
    yum:
      name:
        - curl
        - wget
        - bind-utils
        - telnet
      state: installed
