---
- hosts: group1
  tasks:
   - name: Install the package
     yum:
       name: nmap
       state: present
       use_backend: yum
       
       
#    - name: Gather the rpm package facts
#      package_facts:
#        manager: auto

#    - name: Print the rpm package facts
#      debug:
#        var: ansible_facts.packages
